name: Build TerracottaROM (all devices)

on:
  workflow_dispatch:

jobs:
  gts7fewifi:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare Symlinks
        run: |
              mkdir -p /home/runner/actions-runner/out/tools /home/runner/actions-runner/out/fw /home/runner/actions-runner/out/odin
              mkdir out
              rm -rf /home/runner/actions-runner/out/odin out/fw out/tools
              ln -s /home/runner/actions-runner/out/odin out/odin || true
              ln -s /home/runner/actions-runner/out/fw out/fw || true

      - name: Prepare tools (1x rebuild)
        run: |
             rm -rf /home/runner/actions-runner/out/tools
             mkdir /home/runner/actions-runner/out/tools
             ln -s /home/runner/actions-runner/out/tools out/tools

      - name: Set up build environment
        run: |
             sudo apt update
             DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
             p7zip-full jq attr ccache clang ffmpeg golang \
             libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev \
             libzstd-dev lld jq protobuf-compiler pcre2-utils webp cmake \
             curl xxd patchelf flex bison libarchive-tools build-essential python3-venv device-tree-compiler openjdk-21-jdk
             sudo apt install linux-modules-extra-$(uname -r)
             sudo modprobe erofs f2fs
             git config --global user.name "github-actions[bot]"
             git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
             echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/platform.pk8
             echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/platform.x509.pem

      - name: Build ROM
        run: |
             source ./buildenv.sh gts7fewifi
             run_cmd make_rom

