name: Build TerracottaROM (selection)

on:
  workflow_dispatch:
    inputs:
      device:
        description: "Select device to build"
        required: true
        type: choice
        options:
          - gts7xlwifi
          - gts7lwifi
          - gts7xl
          - gts7l
          - gts7fewifi

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare Symlinks
        run: |
          mkdir -p /home/runner/out/tools /home/runner/out/fw /home/runner/out/odin
          mkdir -p out
          rm -rf out/odin out/fw out/tools
          ln -s /home/runner/out/odin out/odin || true
          ln -s /home/runner/out/fw out/fw || true

      - name: Prepare tools (force rebuild)
        run: |
          rm -rf /home/runner/out/tools
          mkdir -p /home/runner/out/tools
          ln -s /home/runner/out/tools out/tools

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
          p7zip-full jq attr ccache clang ffmpeg golang \
          libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev \
          libzstd-dev lld jq protobuf-compiler pcre2-utils webp cmake \
          curl xxd patchelf flex bison libarchive-tools build-essential python3.13-venv device-tree-compiler openjdk-21-jdk
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/platform.pk8
          echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/platform.x509.pem

      - name: Build ROM
        run: |
          DEVICE="${{ github.event.inputs.device }}"
          source ./buildenv.sh "$DEVICE"
          run_cmd make_rom

      - name: Upload ROM
        run: |
          DEVICE="${{ github.event.inputs.device }}"
          mega-put -c out/*.zip "TerracottaROM/${DEVICE}/$(date +%m.%d.%Y)/"
          rm -rf out/target out/*.zip
